from django.db import models


class Data(models.Model):
	ID_EDIT = models.CharField(max_length=300, blank=True, null=True)
	ANNO = models.IntegerField(blank=True, null=True)
	PESO = models.CharField(max_length=300, blank=True, null=True)
	GENERE = models.CharField(max_length=300, blank=True, null=True)
	ETA = models.IntegerField(blank=True, null=True)
	PROVINCIA_RESIDENZA = models.CharField(max_length=300, blank=True, null=True)
	COMUNE_RESIDENZA = models.CharField(max_length=300, blank=True, null=True)
	GIOCO = models.CharField(max_length=300, blank=True, null=True)
	NASCONDI_ENTITA_DENARO = models.CharField(max_length=300, blank=True, null=True)
	IMPULSO_A_SPENDERE_DI_PIU = models.CharField(max_length=300, blank=True, null=True)
	PROVATO_FUMARE = models.CharField(max_length=300, blank=True, null=True)
	ATTUALMENTE_FUMI = models.CharField(max_length=300, blank=True, null=True)
	NUMERO_SIGARETTE = models.CharField(max_length=300, blank=True, null=True)
	ANNI_FUMO = models.CharField(max_length=300, blank=True, null=True)
	BEVUTO_VITA = models.CharField(max_length=300, blank=True, null=True)
	UBRIACO_ANNO = models.CharField(max_length=300, blank=True, null=True)
	FREQUENZA_UBRIACATO_ANNO = models.CharField(max_length=300, blank=True, null=True)
	BINGE_MESE = models.CharField(max_length=300, blank=True, null=True)
	FREQ_BINGE_MESE = models.CharField(max_length=300, blank=True, null=True)
	PRIMA_SOSTANZA = models.CharField(max_length=300, blank=True, null=True)
	ETA_PRIMO_USO_SOSTANZA = models.CharField(max_length=300, blank=True, null=True)
	FREQUENZA_GUIDA = models.CharField(max_length=300, blank=True, null=True)
	GUIDA_TIPO_MEZZO = models.CharField(max_length=300, blank=True, null=True)
	ALMENO_1_INCIDENTE = models.CharField(max_length=300, blank=True, null=True)
	NUM_INCIDENTI = models.CharField(max_length=300, blank=True, null=True)
	GUIDA_CELL = models.CharField(max_length=300, blank=True, null=True)
	GUIDA_SIGARETTA = models.CharField(max_length=300, blank=True, null=True)
	GUIDA_UBRIACO = models.CharField(max_length=300, blank=True, null=True)
	GUIDA_UBRIACO_VOLTE = models.CharField(max_length=300, blank=True, null=True)
	GUIDA_DOPO_DROGA = models.CharField(max_length=300, blank=True, null=True)
	VOLTE_GUIDA_DOPO_DROGA = models.CharField(max_length=300, blank=True, null=True)
	SU_MEZZO_CON_UBRIACO = models.CharField(max_length=300, blank=True, null=True)
	VOLTE_CON_UBRIACO_GUIDA = models.CharField(max_length=300, blank=True, null=True)
	SU_MEZZO_CON_DROGATO = models.CharField(max_length=300, blank=True, null=True)
	VOLTE_SU_MEZZO_CON_DROGATO = models.CharField(max_length=300, blank=True, null=True)
	SUBITO_PREPOTENZE = models.CharField(max_length=300, blank=True, null=True)
	ATTIVITA_FISICA = models.CharField(max_length=300, blank=True, null=True)
	ATTIVITA_SPORTIVA = models.CharField(max_length=300, blank=True, null=True)
	TIPO_SPORT = models.CharField(max_length=300, blank=True, null=True)
	FREQ_SPORT = models.CharField(max_length=300, blank=True, null=True)
	RAPPORTO_SESSUALE = models.CharField(max_length=300, blank=True, null=True)
	ANNI_PRIMO_RAPPORTO = models.CharField(max_length=300, blank=True, null=True)
	NUMERO_PARTNER = models.CharField(max_length=300, blank=True, null=True)
	USO_ALCOL_DROGA_PRIMA_SESSO = models.CharField(max_length=300, blank=True, null=True)
	USO_PRESERVATIVO = models.CharField(max_length=300, blank=True, null=True)
	BMI = models.CharField(max_length=300, blank=True, null=True)
	BMI_4CLASSI = models.CharField(max_length=300, blank=True, null=True)
	BMI_6CLASSI = models.CharField(max_length=300, blank=True, null=True)
	PESO_CORPOREO = models.CharField(max_length=300, blank=True, null=True)
	ALTEZZA = models.CharField(max_length=300, blank=True, null=True)
	CONSUMO_VERDURA = models.CharField(max_length=300, blank=True, null=True)
	CONSUMO_FRUTTA = models.CharField(max_length=300, blank=True, null=True)
	PORZ_FRUTTA_E_VERDURA = models.CharField(max_length=300, blank=True, null=True)
	SOSTANZE_VITA = models.CharField(max_length=300, blank=True, null=True)
	GHB_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	CANNA_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	ECSTASY_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	AMFETAMINE_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	LSD_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	COCA_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	FUNGHI_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	POPPER_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	EROINA_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	KETAMINA_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	CRACK_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	ANABOL_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	PILLOLE_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	SMART_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	ALTRE_SOST_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	ECST_GHB_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	ANAB_ENERGY_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	CANNAB_SINT_1_VOLTA = models.CharField(max_length=300, blank=True, null=True)
	USO_SOST_NEI_30_GG = models.CharField(max_length=300, blank=True, null=True)
	GHB_30_GG = models.CharField(max_length=300, blank=True, null=True)
	CANNA_30_GG = models.CharField(max_length=300, blank=True, null=True)
	ECSTASY_30_GG = models.CharField(max_length=300, blank=True, null=True)
	AMFETAMINE_30_GG = models.CharField(max_length=300, blank=True, null=True)
	LSD_30_GG = models.CharField(max_length=300, blank=True, null=True)
	COCA_30_GG = models.CharField(max_length=300, blank=True, null=True)
	FUNGHI_30_GG = models.CharField(max_length=300, blank=True, null=True)
	POPPER_30_GG = models.CharField(max_length=300, blank=True, null=True)
	EROINA_30_GG = models.CharField(max_length=300, blank=True, null=True)
	KETAMINA_30_GG = models.CharField(max_length=300, blank=True, null=True)
	CRACK_30_GG = models.CharField(max_length=300, blank=True, null=True)
	ANABOLIZZ_30_GG = models.CharField(max_length=300, blank=True, null=True)
	PILLOLE_30_GG = models.CharField(max_length=300, blank=True, null=True)
	SMART_30_GG = models.CharField(max_length=300, blank=True, null=True)
	ALTRO_30_GG = models.CharField(max_length=300, blank=True, null=True)
	ECSTASY_GHB_30_GG = models.CharField(max_length=300, blank=True, null=True)
	ANABOL_ENERGY_30_GG = models.CharField(max_length=300, blank=True, null=True)
	CANNAB_SINT_30_GG = models.CharField(max_length=300, blank=True, null=True)

	def __str__(self):
		return self.ID_EDIT
