from rest_framework import serializers
from .models import Data


class DataSerializer(serializers.ModelSerializer):
	class Meta:
		model = Data
		fields = ('ID_EDIT', 'ANNO', 'PESO', 'GENERE', 'ETA', 'PROVINCIA_RESIDENZA', 'COMUNE_RESIDENZA', 'GIOCO',
		          'NASCONDI_ENTITA_DENARO', 'IMPULSO_A_SPENDERE_DI_PIU', 'PROVATO_FUMARE', 'ATTUALMENTE_FUMI',
		          'NUMERO_SIGARETTE', 'ANNI_FUMO', 'BEVUTO_VITA', 'UBRIACO_ANNO', 'FREQUENZA_UBRIACATO_ANNO',
		          'BINGE_MESE', 'FREQ_BINGE_MESE', 'PRIMA_SOSTANZA', 'ETA_PRIMO_USO_SOSTANZA', 'FREQUENZA_GUIDA',
		          'GUIDA_TIPO_MEZZO', 'ALMENO_1_INCIDENTE', 'NUM_INCIDENTI', 'GUIDA_CELL', 'GUIDA_SIGARETTA',
		          'GUIDA_UBRIACO', 'GUIDA_UBRIACO_VOLTE', 'GUIDA_DOPO_DROGA', 'VOLTE_GUIDA_DOPO_DROGA',
		          'SU_MEZZO_CON_UBRIACO', 'VOLTE_CON_UBRIACO_GUIDA', 'SU_MEZZO_CON_DROGATO',
		          'VOLTE_SU_MEZZO_CON_DROGATO', 'SUBITO_PREPOTENZE', 'ATTIVITA_FISICA', 'ATTIVITA_SPORTIVA',
		          'TIPO_SPORT', 'FREQ_SPORT', 'RAPPORTO_SESSUALE', 'ANNI_PRIMO_RAPPORTO', 'NUMERO_PARTNER',
		          'USO_ALCOL_DROGA_PRIMA_SESSO', 'USO_PRESERVATIVO', 'BMI', 'BMI_4CLASSI', 'BMI_6CLASSI',
		          'PESO_CORPOREO', 'ALTEZZA', 'CONSUMO_VERDURA', 'CONSUMO_FRUTTA', 'PORZ_FRUTTA_E_VERDURA',
		          'SOSTANZE_VITA', 'GHB_1_VOLTA', 'CANNA_1_VOLTA', 'ECSTASY_1_VOLTA', 'AMFETAMINE_1_VOLTA',
		          'LSD_1_VOLTA', 'COCA_1_VOLTA', 'FUNGHI_1_VOLTA', 'POPPER_1_VOLTA', 'EROINA_1_VOLTA',
		          'KETAMINA_1_VOLTA', 'CRACK_1_VOLTA', 'ANABOL_1_VOLTA', 'PILLOLE_1_VOLTA', 'SMART_1_VOLTA',
		          'ALTRE_SOST_1_VOLTA', 'ECST_GHB_1_VOLTA', 'ANAB_ENERGY_1_VOLTA', 'CANNAB_SINT_1_VOLTA',
		          'USO_SOST_NEI_30_GG', 'GHB_30_GG', 'CANNA_30_GG', 'ECSTASY_30_GG', 'AMFETAMINE_30_GG', 'LSD_30_GG',
		          'COCA_30_GG', 'FUNGHI_30_GG', 'POPPER_30_GG', 'EROINA_30_GG', 'KETAMINA_30_GG', 'CRACK_30_GG',
		          'ANABOLIZZ_30_GG', 'PILLOLE_30_GG', 'SMART_30_GG', 'ALTRO_30_GG', 'ECSTASY_GHB_30_GG',
		          'ANABOL_ENERGY_30_GG', 'CANNAB_SINT_30_GG')
